FROM debian

MAINTAINER cmbuyamb <cmbuyamb@student.wtc.co.za>

RUN apt-get update && apt-get upgrade -y && apt-get install -y nodejs npm git vim emacs

RUN npm install yarn --global && npm install npm --global